version: '3.8'

services:
  frontend:
    container_name: frontend
    volumes:
      - react_build:/frontend/dist 
    build:
      context: ./frontend
    ports: 
      - "8080:8080"
    command: npm run dev
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
  rabbitmq:
    restart: always
    ports:
      - '5672:5672'
    hostname: pacmanweb-rabbit
    image:
      rabbitmq:3-management
  celery:
    restart: always
    container_name: celery
    command: celery -A pacmanweb.celery_app worker --loglevel=info
    build:
      context: .
      dockerfile: ./pacmanweb/Dockerfile
    volumes:
      - .:/app
    environment: 
      - CUR_IP="152.58.33.43"
    depends_on:
      - redis
      - rabbitmq
    links:
      - redis:redis
      - rabbitmq:rabbitmq
  backend:
    platform: linux/amd64
    container_name: backend
    build:
      context: .
      dockerfile: ./pacmanweb/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .flaskenv
    depends_on:
      - redis
      - rabbitmq
      - celery
    links:
      - redis:redis
      - rabbitmq:rabbitmq
    command: gunicorn 'pacmanweb:create_app()' --access-logfile=- --bind 0.0.0.0:8000
   
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro 
      - react_build:/var/www/frontend 
    depends_on:
      - backend
      - frontend  
      - celery
      - redis

volumes:
  react_build:
