version: '3.8'

services:
  redis:
    image: redis:7-alpine

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./pacmanweb/Dockerfile
    image: pacmanweb
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/
    ports:
      - 5010:5000
    env_file:
      - .flaskenv
    depends_on:
      - redis
  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./pacmanweb/Dockerfile
    image: pacmanweb
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/
    ports:
      - 5010:5000
    env_file:
      - .flaskenv
    depends_on:
      - redis


