version: '3.8'
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - react_build:/frontend/dist 
    env_file:
      - .env.prod
    ports: 
      - "8080:8080"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    hostname: pacmanweb-rabbit
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./pacmanweb/Dockerfile
    volumes:
      - .:/app
      - ./.env.prod:/app/.env
    env_file:
      - .env.prod
    command: celery -A pacmanweb.celery_app worker --loglevel=info -c 10 -E
    depends_on:
      - redis
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./pacmanweb/Dockerfile
    volumes:
      - .:/app
      - ./.env.prod:/app/.env
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - redis
      - rabbitmq
      - celery
    command: gunicorn 'pacmanweb:create_app()' --access-logfile=- --bind 0.0.0.0:8000 --timeout 120 --worker-class gevent
    environment:
      - PYTHONUNBUFFERED=1

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: ./pacmanweb/Dockerfile
    volumes:
      - .:/app
      - ./.env.prod:/app/.env
    env_file:
      - .env.prod
    command: celery -A pacmanweb.celery_app flower
    ports:
      - '5555:5555'
    depends_on:
      - redis
      - rabbitmq
      - celery
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./nginx/htpasswd_docs:/etc/nginx/htpasswd_docs:ro
      - ${SSL_CERT_FILE}:/etc/nginx/ssl/cert.pem:ro
      - ${SSL_KEY_FILE}:/etc/nginx/ssl/key.pem:ro
      - react_build:/var/www/frontend
      - docs_build:/usr/share/nginx/docs
    env_file:
      - .env.prod
    depends_on:
      - backend
      - frontend  
      - celery
      - redis
      - flower

volumes:
  react_build:
  docs_build:
  redis_data:
  rabbitmq_data: