name: Frontend Tests

on:
    workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: 
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Use Latest Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'node'

    - name: Go to Frontend Directory
    run: cd frontend

    - name: Install dependencies
      run: npm install

 
    - name: Run frontend tests
      run: npm test